// This file is automatically generated from your CSS. Any edits will be overwritten.
export const home: string;
export const pageEnter: string;
export const pageEnterActive: string;
export const pageExit: string;
export const pageExitActive: string;
